<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "trader-theme"
 *
 * Auto generated by Extension Builder 2016-12-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Trader Theme',
    'description' => 'Template addition.',
    'category' => 'templates',
    'author' => 'Gert-jan Dikkescheij',
    'author_email' => 'gerry@newred.ch',
    'author_company' => 'Newred sagl',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '7.6.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
            't3sbootstrap' => '3.0.0-3.9.9',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
